"""Which AI runs the headless jobs. config.json "agent": "claude" (default) or "grok".

The job scripts (refresh/chase/voice/people) name tools logically - "slack.read_channel",
"gmail.search_threads" - and call run(prompt, tools). This module maps those names to the
agent's own tool ids and invokes the right CLI.

Grok: Slack is opt-in (config.json "use_slack"). Off, the Slack plugin is not started and
doctor does not probe it. Vercel is never started. Jobs pass --effort low because the Grok
CLI defaults to xhigh. Gmail is the bundled gmail_mcp.py server (not Claude's connector).
"""
import json, os, shutil, subprocess, sys
from pathlib import Path

from .paths import ROOT
WIN = sys.platform == "win32"
_GROK_JOB_HOME = ROOT / "state" / "grok-home"

# logical "service.tool" -> per-agent fully-qualified tool id
_FMT = {
    "claude": {"slack": "mcp__plugin_slack_slack__slack_{}", "gmail": "mcp__claude_ai_Gmail__{}"},
    "grok":   {"slack": "slack__slack_{}",                   "gmail": "gmail__{}"},
}

# Grok CLI defaults to xhigh; Open Loops jobs are unattended JSON, not coding.
_GROK_DISALLOWED = (
    "Agent,run_terminal_cmd,search_replace,read_file,todo_write,write,"
    "grep,list_dir,web_search,web_fetch"
)


def _cfg():
    f = ROOT / "config.json"
    return json.loads(f.read_text(encoding="utf-8-sig")) if f.exists() else {}


def name():
    return (_cfg().get("agent") or "claude").strip().lower()


def display_name():
    return {"claude": "Claude", "grok": "Grok"}.get(name(), name().capitalize())


def cli():
    """Path or command for the agent's CLI (also used to open its sign-in terminal)."""
    if name() == "grok":
        # grok installs to ~/.grok/bin, which Finder/launchd PATHs usually lack
        return shutil.which("grok") or str(Path.home() / ".grok" / "bin" / "grok")
    return "claude"


def use_slack():
    """Grok only: Slack plugin is off unless the user ticks Use Slack in Settings."""
    return bool(_cfg().get("use_slack"))


def slack_enabled():
    """Whether jobs should pass Slack tools. Claude unchanged (still gated on slack_self_id)."""
    return True if name() != "grok" else use_slack()


def grok_job_env():
    """Env for headless Grok: skip Vercel always, skip Slack unless use_slack.

    Grok loads Slack/Vercel from Claude plugins; project .grok/config.toml cannot
    disable those. disabled_mcp_servers in a job-local GROK_HOME does.
    """
    home = _GROK_JOB_HOME
    home.mkdir(parents=True, exist_ok=True)
    src = Path.home() / ".grok"
    for name_ in ("auth.json", "trusted_folders.toml", "trusted_folders.toml.lock"):
        origin, dest = src / name_, home / name_
        if origin.exists() or origin.is_symlink():
            if dest.exists() or dest.is_symlink():
                dest.unlink()
            dest.symlink_to(origin)
    disabled = ["vercel"] if use_slack() else ["vercel", "slack"]
    (home / "config.toml").write_text(
        "# Generated by Open Loops for headless Grok jobs. Do not edit.\n"
        "disabled_mcp_servers = " + json.dumps(disabled) + "\n",
        encoding="utf-8")
    env = dict(os.environ)
    env["GROK_HOME"] = str(home)
    env["GROK_CLAUDE_AGENTS_ENABLED"] = "0"
    env["GROK_CLAUDE_SKILLS_ENABLED"] = "0"
    env["GROK_CURSOR_SKILLS_ENABLED"] = "0"
    env["GROK_CURSOR_AGENTS_ENABLED"] = "0"
    return env


def _qualify(tools):
    fmt = _FMT.get(name()) or _FMT["claude"]
    return [fmt[t.split(".", 1)[0]].format(t.split(".", 1)[1]) for t in tools]


def run(prompt, tools):
    """One unattended prompt with only the given MCP tools allowed -> CompletedProcess."""
    if name() == "grok":
        # --cwd matters: .grok/config.toml there defines the bundled Gmail MCP server
        # (gmail_mcp.py, which does its own Google auth via gmail_auth.py).
        args = [cli(), "--cwd", str(ROOT), "-p", prompt, "--verbatim",
                "--output-format", "plain", "--max-turns", "50", "--effort", "low",
                "--disable-web-search", "--no-plan", "--no-subagents", "--no-auto-update",
                "--tools", "search_tool,use_tool",
                "--disallowed-tools", _GROK_DISALLOWED]
        for t in _qualify(tools):
            args += ["--allow", f"MCPTool({t})"]
        return subprocess.run(args, capture_output=True, text=True,
                              encoding="utf-8", errors="replace", env=grok_job_env(), shell=WIN)
    # shell=True only on Windows, to resolve claude.cmd (npm shim) via PATH
    return subprocess.run(["claude", "-p", "--output-format", "text",
                           "--allowedTools", ",".join(_qualify(tools))],
                          input=prompt, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", shell=WIN)
